import '../styles/globals.css'

export const metadata = {
  title: 'Nino Berber | Portfolio',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="bg-white font-['Sora'] text-black dark:bg-lightDark dark:text-white">
        {children}
      </body>
    </html>
  )
}
