import '../styles/globals.css'
import { Sora } from 'next/font/google'

const sora = Sora({
  weight: '400',
  preload: false,
})

export const metadata = {
  title: 'Nino Berber | Portfolio',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="bg-white text-black dark:bg-lightDark dark:text-white">
        {children}
      </body>
    </html>
  )
}
