local_backend: true
backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: 'public/uploads' # Media files will be stored in the repo under static/images/uploads
public_folder: '/uploads' # The src attribute for uploaded media will begin with /images/uploads
slug:
  encoding: ascii
  clean_accents: true

collections:
  - name: projects
    label: Projets
    folder: src/content/projects
    create: true
    editor: { preview: false }
    fields:
      - label: Projets
        name: projects
        widget: list
        summary: '{{title}}'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Description', name: 'description', widget: 'text' }
          - { label: 'Image', name: 'image', widget: 'image' }
          - { label: 'GitHub Link', name: 'linkGit', widget: 'string' }
          - { label: 'Project Link', name: 'link', widget: 'string' }

  - name: Tools
    label: Outils
    folder: src/content/tools
    create: true
    editor: { preview: false }
    fields:
      - label: Outils
        name: tools
        widget: list
        summary: '{{title}}'
        fields:
          - label: Brouillon
            name: draft
            widget: boolean
            default: false
          - label: Nom
            name: name
            widget: string
          - label: Image
            name: image
            widget: image
