backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
publish_mode: editorial_workflow
media_folder: 'public/uploads' # Media files will be stored in the repo under static/images/uploads
public_folder: '/uploads' # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: projects
    label: Projects
    folder: 'content/projects'
    create: true
    slug: '{{slug}}'
    fields:
      - { label: Draft, name: draft, widget: 'boolean', default: false }
      - { label: Title, name: title, widget: string }
      - { label: Body, name: body, widget: markdown }
      - {
          label: Technologies,
          name: technos,
          widget: relation,
          collection: technos,
          multiple: true,
        }
      - { label: Image, name: image, widget: image }
      - { label: Date, name: date, widget: datetime }
      - { label: Tags, name: tags, widget: list }
