local_backend: true
backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: 'public/uploads' # Media files will be stored in the repo under static/images/uploads
public_folder: '/uploads' # The src attribute for uploaded media will begin with /images/uploads
slug:
  encoding: ascii
  clean_accents: true

collections:
  - name: introText
    label: Texte d'introduction
    folder: src/content/intro
    create: true
    editor: { preview: false }
    fields:
      - { label: 'Titre principal', name: 'mainTitle', widget: 'string' }
      - { label: 'Titre secondaire', name: 'subtitle', widget: 'string' }
      - { label: 'Call-To-Action', name: 'cta', widget: 'string' }

  - name: projects
    label: Projets
    folder: src/content
    create: true
    editor: { preview: false }
    fields:
      - label: Projets
        name: projects
        widget: list
        summary: '{{title}}'
        fields:
          - label: Brouillon
            name: draft
            widget: boolean
            default: false
          - label: Titre
            name: title
            widget: string
          - label: Description
            name: description
            widget: text
          - label: Lien
            name: link
            widget: string
          - label: Lien git
            name: linkGit
            widget: string
          - label: Image
            name: image
            widget: image
